/**
 ******************************************************************************
 * @file    esp_link.c
 * @brief   M4 side of the UART link to the ESP32-S3 display (§8).
 ******************************************************************************
 */

#include "esp_link.h"
#include "main.h"
#include "cmsis_os.h"
#include "FreeRTOS.h"
#include "task.h"
#include "shared_state.h"
#include <string.h>

/* huart2 is generated by CubeMX after the .ioc is regenerated with USART2
 * assigned to CortexM4. Until then this extern is unresolved and the link
 * will fail — that's the user's signal to apply the .ioc changes. */
extern UART_HandleTypeDef huart2;

/* ========================================================================
 *  Module state
 * ===================================================================== */

/* RX side */
static uint8_t           s_rx_ring[ESPLINK_RX_RING_SIZE];
static volatile uint16_t s_rx_dma_head_last = 0u;   /* last DMA head observed */
static volatile uint16_t s_rx_parser_tail   = 0u;   /* parser consume index */
static TaskHandle_t      s_rx_task_handle   = NULL;

/* TX side */
static uint8_t           s_tx_buf[ESPLINK_MAX_FRAME];
static volatile uint8_t  s_tx_busy = 0u;
static uint32_t          s_tx_seq  = 0u;

/* Parser state machine */
typedef enum {
    P_SYNC0,
    P_SYNC1,
    P_TYPE,
    P_LEN,
    P_PAYLOAD,
    P_CRC
} parse_state_t;

static parse_state_t s_pstate = P_SYNC0;
static uint8_t       s_pmsg_type = 0u;
static uint8_t       s_pmsg_len  = 0u;
static uint8_t       s_pbuf[ESPLINK_MAX_PAYLOAD];
static uint16_t      s_pbuf_idx  = 0u;
static uint8_t       s_pcrc      = 0u;

/* RX-side fault counters (also bumped into g_shared.m4_fault_flags) */
static uint32_t s_crc_err   = 0u;
static uint32_t s_len_err   = 0u;
static uint32_t s_type_err  = 0u;
static uint32_t s_range_err = 0u;

/* ========================================================================
 *  Helpers
 * ===================================================================== */

static void send_ack(uint8_t status, uint8_t echoed_type);

/* Compute CRC over TYPE + LEN + PAYLOAD (matches sender semantic). */
static inline uint8_t crc_frame(uint8_t type, uint8_t len,
                                 const uint8_t *payload)
{
    uint8_t tmp[ESPLINK_MAX_PAYLOAD + 2];
    tmp[0] = type;
    tmp[1] = len;
    if (len) memcpy(&tmp[2], payload, len);
    return esplink_crc8(tmp, (size_t)(2u + len));
}

/* Build and TX a frame. Returns 0 on success, non-zero if TX is busy
 * (frame dropped — oldest-frame-dropped policy per checklist §8 TX). */
static int send_frame(uint8_t type, const void *payload, uint8_t len)
{
    if (len > ESPLINK_MAX_PAYLOAD) { return -1; }
    if (s_tx_busy) { return -2; }   /* drop frame */

    s_tx_buf[0] = ESPLINK_SYNC0;
    s_tx_buf[1] = ESPLINK_SYNC1;
    s_tx_buf[2] = type;
    s_tx_buf[3] = len;
    if (len) memcpy(&s_tx_buf[4], payload, len);
    s_tx_buf[4 + len] = crc_frame(type, len, (const uint8_t *)payload);

    s_tx_busy = 1u;
    if (HAL_UART_Transmit_DMA(&huart2, s_tx_buf,
                              (uint16_t)(ESPLINK_OVERHEAD + len)) != HAL_OK) {
        s_tx_busy = 0u;
        return -3;
    }
    return 0;
}

static void send_ack(uint8_t status, uint8_t echoed_type)
{
    EspAck_t ack = {0};
    ack.status      = status;
    ack.echoed_type = echoed_type;
    ack.command_seq = g_shared.command_seq;
    (void)send_frame(ESPLINK_TYPE_ACK, &ack, sizeof(ack));
}

/* ========================================================================
 *  RX: validate then apply. Shared-state writes go under a FreeRTOS
 *  critical section to serialize against the other M4 writers
 *  (tcpip_thread, watchdog task). M7 reads lock-free via the
 *  fields-before-command_seq write ordering.
 * ===================================================================== */

static void apply_set_mode(const uint8_t *p, uint8_t len)
{
    if (len != sizeof(EspCmdMode_t)) {
        s_len_err++;
        taskENTER_CRITICAL();
        g_shared.m4_fault_flags |= M4_FAULT_UART_BAD_CRC;   /* RMW: serialize vs other M4 writers */
        taskEXIT_CRITICAL();
        send_ack(ESPLINK_ACK_BAD_LEN, ESPLINK_TYPE_SET_MODE);
        return;
    }
    EspCmdMode_t cmd; memcpy(&cmd, p, sizeof(cmd));

    /* Range check */
    if (cmd.mode > CTRL_MODE_POT_VELOCITY) {
        s_range_err++;
        send_ack(ESPLINK_ACK_OUT_OF_RANGE, ESPLINK_TYPE_SET_MODE);
        return;
    }

    taskENTER_CRITICAL();
    g_shared.command_mode = cmd.mode;  /* payload first ... */
    g_shared.cmd_set_mode = 1u;        /* ... then the one-shot request flag (F10) */
    g_shared.command_seq++;
    taskEXIT_CRITICAL();

    send_ack(ESPLINK_ACK_OK, ESPLINK_TYPE_SET_MODE);
}

static void apply_set_setpoint(const uint8_t *p, uint8_t len)
{
    if (len != sizeof(EspCmdSetpoint_t)) {
        s_len_err++;
        send_ack(ESPLINK_ACK_BAD_LEN, ESPLINK_TYPE_SET_SETPOINT);
        return;
    }
    EspCmdSetpoint_t cmd; memcpy(&cmd, p, sizeof(cmd));

    /* Sane-value bound */
    float v = cmd.setpoint;
    if (!(v >= -ESPLINK_SETPOINT_MAX_ABS && v <= ESPLINK_SETPOINT_MAX_ABS)) {
        s_range_err++;
        send_ack(ESPLINK_ACK_OUT_OF_RANGE, ESPLINK_TYPE_SET_SETPOINT);
        return;
    }

    taskENTER_CRITICAL();
    g_shared.setpoint = v;
    g_shared.command_seq++;
    taskEXIT_CRITICAL();

    send_ack(ESPLINK_ACK_OK, ESPLINK_TYPE_SET_SETPOINT);
}

static void apply_lqr_delta(const uint8_t *p, uint8_t len)
{
    if (len != sizeof(EspCmdGainDelta_t)) {
        s_len_err++;
        send_ack(ESPLINK_ACK_BAD_LEN, ESPLINK_TYPE_LQR_DELTA);
        return;
    }
    EspCmdGainDelta_t cmd; memcpy(&cmd, p, sizeof(cmd));

    if (cmd.index > ESPLINK_GAIN_INDEX_MAX) {
        s_range_err++;
        send_ack(ESPLINK_ACK_OUT_OF_RANGE, ESPLINK_TYPE_LQR_DELTA);
        return;
    }
    float d = cmd.delta;
    if (!(d >= -ESPLINK_GAIN_DELTA_MAX && d <= ESPLINK_GAIN_DELTA_MAX)) {
        s_range_err++;
        send_ack(ESPLINK_ACK_OUT_OF_RANGE, ESPLINK_TYPE_LQR_DELTA);
        return;
    }

    taskENTER_CRITICAL();
    /* Accumulate (nudge semantics, same as the MATLAB path) with the same
     * +/-50 saturation — assignment pinned the gain at the last delta. */
    float acc = g_shared.lqr_gain_delta[cmd.index] + d;
    if (acc >  50.0f) acc =  50.0f;
    if (acc < -50.0f) acc = -50.0f;
    g_shared.lqr_gain_delta[cmd.index] = acc;
    g_shared.command_seq++;
    taskEXIT_CRITICAL();

    send_ack(ESPLINK_ACK_OK, ESPLINK_TYPE_LQR_DELTA);
}

static void apply_clear_errors(uint8_t len)
{
    (void)len;
    g_shared.m4_fault_flags = 0u;

    taskENTER_CRITICAL();
    g_shared.cmd_clear_errors = 1u;   /* M7 picks this up: sends Odrive_ClearErrors() over CAN */
    g_shared.command_seq++;
    taskEXIT_CRITICAL();

    send_ack(ESPLINK_ACK_OK, ESPLINK_TYPE_CLEAR_ERRORS);
}

static void apply_home_esp(void)
{
    taskENTER_CRITICAL();
    g_shared.cmd_home = 1u;
    g_shared.command_seq++;
    taskEXIT_CRITICAL();
    send_ack(ESPLINK_ACK_OK, ESPLINK_TYPE_HOME);
}

/* Capture the pendulum upright zero (operator holds link 1 vertical).
 * Same request byte the MATLAB path (0x08) sets; M7 consumes it in
 * pot_ctrl.c via StateEst_ZeroUpright(). */
static void apply_zero_upright_esp(void)
{
    taskENTER_CRITICAL();
    g_shared.cmd_zero_upright = 1u;
    g_shared.command_seq++;
    taskEXIT_CRITICAL();
    send_ack(ESPLINK_ACK_OK, ESPLINK_TYPE_ZERO_UPRIGHT);
}

/* Dispatch a fully validated frame (header + payload + CRC verified). */
static void dispatch_frame(uint8_t type, const uint8_t *payload, uint8_t len)
{
    switch (type) {
    case ESPLINK_TYPE_SET_MODE:     apply_set_mode(payload, len);     break;
    case ESPLINK_TYPE_SET_SETPOINT: apply_set_setpoint(payload, len); break;
    case ESPLINK_TYPE_LQR_DELTA:    apply_lqr_delta(payload, len);    break;
    case ESPLINK_TYPE_CLEAR_ERRORS: apply_clear_errors(len);           break;
    case ESPLINK_TYPE_HOME:         apply_home_esp();                  break;
    case ESPLINK_TYPE_ZERO_UPRIGHT: apply_zero_upright_esp();          break;
    default:
        s_type_err++;
        send_ack(ESPLINK_ACK_BAD_TYPE, type);
        break;
    }
}

/* ========================================================================
 *  RX byte-stream parser (state machine)
 * ===================================================================== */

static void parser_reset(void)
{
    s_pstate    = P_SYNC0;
    s_pmsg_type = 0u;
    s_pmsg_len  = 0u;
    s_pbuf_idx  = 0u;
    s_pcrc      = 0u;
}

static void parser_feed(uint8_t b)
{
    switch (s_pstate) {
    case P_SYNC0:
        if (b == ESPLINK_SYNC0) s_pstate = P_SYNC1;
        break;

    case P_SYNC1:
        if      (b == ESPLINK_SYNC1) s_pstate = P_TYPE;
        else if (b == ESPLINK_SYNC0) /* stay in SYNC1 */ ;
        else    s_pstate = P_SYNC0;
        break;

    case P_TYPE:
        s_pmsg_type = b;
        s_pstate    = P_LEN;
        break;

    case P_LEN:
        s_pmsg_len = b;
        if (s_pmsg_len > ESPLINK_MAX_PAYLOAD) {
            s_len_err++;
            taskENTER_CRITICAL();
            g_shared.m4_fault_flags |= M4_FAULT_UART_BAD_CRC;   /* RMW: serialize vs other M4 writers */
            taskEXIT_CRITICAL();
            parser_reset();
            return;
        }
        s_pbuf_idx = 0u;
        s_pstate   = (s_pmsg_len == 0u) ? P_CRC : P_PAYLOAD;
        break;

    case P_PAYLOAD:
        s_pbuf[s_pbuf_idx++] = b;
        if (s_pbuf_idx >= s_pmsg_len) s_pstate = P_CRC;
        break;

    case P_CRC: {
        uint8_t calc = crc_frame(s_pmsg_type, s_pmsg_len, s_pbuf);
        if (calc == b) {
            dispatch_frame(s_pmsg_type, s_pbuf, s_pmsg_len);
        } else {
            s_crc_err++;
            taskENTER_CRITICAL();
            g_shared.m4_fault_flags |= M4_FAULT_UART_BAD_CRC;   /* RMW: serialize vs other M4 writers */
            taskEXIT_CRITICAL();
        }
        parser_reset();
        break;
    }
    }
}

/* Drain the DMA RX ring from parser_tail up to the current DMA head. */
static void parser_drain(void)
{
    /* NDTR counts down from buffer size; head = SIZE - NDTR. */
    uint16_t ndtr = (uint16_t)__HAL_DMA_GET_COUNTER(huart2.hdmarx);
    uint16_t head = (uint16_t)(ESPLINK_RX_RING_SIZE - ndtr);
    while (s_rx_parser_tail != head) {
        parser_feed(s_rx_ring[s_rx_parser_tail]);
        s_rx_parser_tail = (uint16_t)((s_rx_parser_tail + 1u) % ESPLINK_RX_RING_SIZE);
    }
    s_rx_dma_head_last = head;
}

/* ========================================================================
 *  HAL callback hooks (called from ISR context)
 * ===================================================================== */

/* Called from HAL_UARTEx_RxEventCallback on idle-line OR half/full DMA
 * transfer interrupt. We just wake the RX task. */
void EspLink_OnRxIdleOrCpltISR(uint16_t bytes_in_dma)
{
    (void)bytes_in_dma;
    BaseType_t hpw = pdFALSE;
    if (s_rx_task_handle) {
        vTaskNotifyGiveFromISR(s_rx_task_handle, &hpw);
        portYIELD_FROM_ISR(hpw);
    }
}

void EspLink_OnTxCpltISR(void)
{
    s_tx_busy = 0u;
}

/* ========================================================================
 *  Init + tasks
 * ===================================================================== */

void EspLink_Init(void)
{
    parser_reset();
    s_rx_dma_head_last = 0u;
    s_rx_parser_tail   = 0u;
    s_tx_busy          = 0u;
    s_tx_seq           = 0u;

    /* Start DMA RX into circular buffer with idle-line detection. The HAL
     * call configures both half-transfer + transfer-complete + idle-line
     * to fire HAL_UARTEx_RxEventCallback. */
    (void)HAL_UARTEx_ReceiveToIdle_DMA(&huart2, s_rx_ring, ESPLINK_RX_RING_SIZE);

    /* The default HAL_UARTEx_ReceiveToIdle_DMA also enables the half-transfer
     * interrupt which we don't strictly need. Disabling it cuts noise but is
     * harmless either way. Comment out the next line if you'd rather keep it. */
    __HAL_DMA_DISABLE_IT(huart2.hdmarx, DMA_IT_HT);
}

void EspLink_RxTask(void *argument)
{
    (void)argument;
    s_rx_task_handle = xTaskGetCurrentTaskHandle();

    EspLink_Init();

    for (;;) {
        /* Block until idle-line or DMA complete fires from the ISR. Also
         * unblock periodically so a slow-trickling stream still gets parsed
         * (~50 ms is plenty given DMA buffer holds 512 B). */
        ulTaskNotifyTake(pdTRUE, pdMS_TO_TICKS(50));
        parser_drain();
    }
}

void EspLink_TxTask(void *argument)
{
    (void)argument;

    /* Give RX time to start its DMA before we start firing TX frames. */
    osDelay(50);

    EspTelemetry_t pkt;
    TickType_t next = xTaskGetTickCount();

    for (;;) {
        pkt.seq               = s_tx_seq++;
        pkt.timestamp_ms      = HAL_GetTick();

        pkt.link_angle_rad[0] = g_shared.link_angle_rad[0];
        pkt.link_angle_rad[1] = g_shared.link_angle_rad[1];
        pkt.link_angle_rad[2] = g_shared.link_angle_rad[2];
        pkt.cart_position     = g_shared.cart_position;
        pkt.cart_velocity     = g_shared.cart_velocity;
        pkt.motor_command     = g_shared.motor_command;
        pkt.odrive_motor_pos  = g_shared.odrive_motor_pos;

        pkt.loop_count        = g_shared.loop_count;
        pkt.loop_overrun_cnt  = g_shared.loop_overrun_cnt;
        pkt.m7_fault_flags    = g_shared.m7_fault_flags;
        pkt.m4_fault_flags    = g_shared.m4_fault_flags;

        pkt.controller_mode   = g_shared.controller_mode;
        pkt.command_mode      = g_shared.command_mode;
        pkt.rail_state        = g_shared.rail_state;
        pkt._pad              = 0u;

        (void)send_frame(ESPLINK_TYPE_TELEMETRY, &pkt, (uint8_t)sizeof(pkt));

        vTaskDelayUntil(&next, pdMS_TO_TICKS(ESPLINK_TX_PERIOD_MS));
    }
}
